# Generated by Django 4.1.1 on 2022-09-14 21:34

import app.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('country', models.CharField(max_length=50)),
                ('iso2', models.CharField(max_length=10)),
                ('admin_name', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('population_proper', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=33, region=None)),
                ('short_introduction', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('field_of_study', models.CharField(max_length=50)),
                ('degree', models.CharField(choices=[('1', 'Associate'), ('2', "Bachelor's"), ('3', "Master's"), ('4', 'Doctoral')], max_length=50)),
                ('years_of_experience', models.FloatField()),
                ('photo', models.ImageField(upload_to='photos/', validators=[app.models.validate_photo_extension])),
                ('resume', models.FileField(upload_to='resumes/', validators=[app.models.validate_resume_extension])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.city')),
            ],
        ),
    ]
