# Generated by Django 4.1.1 on 2022-09-15 14:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='age',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='field_of_study',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='photo',
            field=models.ImageField(upload_to='files/photos/', validators=[app.models.validate_photo_extension]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='resume',
            field=models.FileField(upload_to='files/resumes/', validators=[app.models.validate_resume_extension]),
        ),
    ]
